'use client';
import { useState } from 'react';
import { X, Sparkles, Copy, Check, Loader2 } from 'lucide-react';

interface Props {
  onClose: () => void;
}

export default function ExecutiveSummaryModal({ onClose }: Props) {
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useState(() => {
    fetch('/api/ai/summary', { method: 'POST' })
      .then(r => r.json())
      .then(d => { setSummary(d.summary); setLoading(false); })
      .catch(() => { setSummary('Unable to generate summary. Please check your API key configuration.'); setLoading(false); });
  });

  async function copy() {
    await navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" />
      <div className="relative glass rounded-2xl w-full max-w-2xl max-h-[80vh] flex flex-col shadow-2xl shadow-black/60 slide-up">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800/60">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-purple-600/20 border border-purple-500/30 flex items-center justify-center">
              <Sparkles size={18} className="text-purple-400" />
            </div>
            <div>
              <h2 className="text-base font-semibold text-slate-200">Executive Summary</h2>
              <p className="text-xs text-slate-500">AI-generated · {today}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {!loading && summary && (
              <button
                onClick={copy}
                className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-slate-200 bg-slate-800/60 hover:bg-slate-700/60 border border-slate-700/60 rounded-lg px-3 py-1.5 transition-all"
              >
                {copied ? <Check size={13} className="text-emerald-400" /> : <Copy size={13} />}
                {copied ? 'Copied!' : 'Copy'}
              </button>
            )}
            <button onClick={onClose} className="text-slate-500 hover:text-slate-300 transition-colors">
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-5">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-16 gap-4">
              <div className="w-12 h-12 rounded-full bg-purple-600/10 border border-purple-500/20 flex items-center justify-center">
                <Loader2 size={22} className="text-purple-400 animate-spin" />
              </div>
              <div className="text-center">
                <p className="text-slate-300 text-sm font-medium">Generating executive summary…</p>
                <p className="text-slate-500 text-xs mt-1">Analysing all portfolio matters with AI</p>
              </div>
            </div>
          ) : (
            <div className="prose prose-invert prose-sm max-w-none">
              {summary.split('\n\n').map((para, i) => (
                <p key={i} className="text-slate-300 text-sm leading-7 mb-4 last:mb-0">
                  {para}
                </p>
              ))}
            </div>
          )}
        </div>

        {/* Footer note */}
        {!loading && (
          <div className="px-6 py-3 border-t border-slate-800/60 flex items-center gap-2 text-xs text-slate-600">
            <Sparkles size={11} />
            Generated by Claude AI · For internal use only · Not legal advice
          </div>
        )}
      </div>
    </div>
  );
}
