import { RegulatoryMatter } from './types';

export const seedMatters: RegulatoryMatter[] = [
  {
    id: '1',
    caseNumber: 'PRX-2023-BR-001',
    companyName: 'OLX Brazil',
    dateStarted: '2023-03-15',
    regulator: 'CADE',
    jurisdiction: 'Brazil',
    area: 'Competition',
    summary: 'CADE investigation into anti-competitive practices in the online classifieds market. OLX Brazil is alleged to have engaged in predatory pricing strategies specifically targeting smaller competitors, with pricing models set below cost to drive rivals out of the market. The investigation also examines potential abuse of dominant position through preferential arrangements with major property developers.',
    potentialExposureAmount: 45000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Fines up to 20% of annual turnover plus potential disgorgement of illegal profits estimated at BRL 225 million.',
    status: 'Under Investigation',
    riskLevel: 'High',
    riskScore: 72,
    riskRationale: 'OLX holds approximately 60% market share in Brazilian classifieds. CADE has broad investigative powers and a track record of significant fines. The predatory pricing allegations are supported by internal pricing documents obtained during dawn raids. Settlement is possible but unlikely in the near term given the scale of alleged conduct.',
    lastUpdated: '2024-05-10',
    submittedBy: 'Carlos Mendes',
  },
  {
    id: '2',
    caseNumber: 'PRX-2023-IN-002',
    companyName: 'Swiggy',
    dateStarted: '2023-06-01',
    regulator: 'CCI',
    jurisdiction: 'India',
    area: 'Antitrust',
    summary: "Competition Commission of India investigation into exclusivity clauses embedded in Swiggy\'s contracts with restaurant partners, allegedly preventing those restaurants from listing on rival food delivery platforms. The CCI is examining whether these exclusivity arrangements constitute an abuse of dominant position in the online food delivery market and whether they foreclose market access for competitors.",
    potentialExposureAmount: 30000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Fines up to 10% of average turnover for three preceding financial years, estimated at USD 30 million, plus mandatory contract modifications.',
    status: 'Under Investigation',
    riskLevel: 'High',
    riskScore: 68,
    riskRationale: "CCI has been increasingly active against platform businesses. Similar cases against Zomato and Amazon have resulted in significant penalties. The exclusivity clauses appear to cover approximately 35% of top-tier restaurant partners. Likelihood of finding dominant position is high given Swiggy\'s 45% market share.",
    lastUpdated: '2024-06-01',
    submittedBy: 'Priya Sharma',
  },
  {
    id: '3',
    caseNumber: 'PRX-2022-BR-003',
    companyName: 'iFood',
    dateStarted: '2022-11-10',
    regulator: 'CADE',
    jurisdiction: 'Brazil',
    area: 'Competition',
    summary: "CADE dominance abuse investigation into iFood\'s market foreclosure strategy through exclusive delivery contracts. iFood is accused of systematically locking restaurants into exclusivity agreements with financial penalties for breach, effectively preventing restaurants from multi-homing on competitor platforms. The investigation has moved to formal litigation phase following failed settlement negotiations.",
    potentialExposureAmount: 85000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Potential fines of BRL 400 million plus structural remedies including mandatory interoperability requirements and contract modifications.',
    status: 'Litigation',
    riskLevel: 'Critical',
    riskScore: 88,
    riskRationale: "iFood controls approximately 80% of the Brazilian food delivery market, making dominance finding almost certain. CADE has documented evidence of exclusivity clauses affecting over 150,000 restaurant partners. The case has entered formal litigation with CADE\'s tribunal, significantly reducing settlement prospects. Structural remedies could materially impact business model.",
    lastUpdated: '2024-07-15',
    submittedBy: 'Rafael Costa',
  },
  {
    id: '4',
    caseNumber: 'PRX-2024-IN-004',
    companyName: 'PayU India',
    dateStarted: '2024-01-20',
    regulator: 'RBI',
    jurisdiction: 'India',
    area: 'Data Privacy',
    summary: "Reserve Bank of India investigation into PayU India\'s non-compliance with data localisation requirements under the RBI\'s Payment and Settlement Systems regulations. Specific concerns relate to payment data storage on overseas servers and inadequate data residency controls for sensitive financial transaction data of Indian customers.",
    potentialExposureAmount: 12000000,
    potentialExposureCriminal: false,
    exposureDescription: 'RBI fines for PSP non-compliance estimated at INR 1 billion plus potential suspension of payment aggregator licence.',
    status: 'Monitoring',
    riskLevel: 'Medium',
    riskScore: 45,
    riskRationale: "PayU has been actively remediating its data architecture to achieve compliance. RBI has generally preferred compliance-focused outcomes over punitive action for payment aggregators that demonstrate good faith remediation efforts. However, the licence suspension risk remains a tail risk that elevates overall concern.",
    lastUpdated: '2024-08-20',
    submittedBy: 'Ankit Verma',
  },
  {
    id: '5',
    caseNumber: 'PRX-2023-US-005',
    companyName: 'Udemy',
    dateStarted: '2023-09-05',
    regulator: 'FTC',
    jurisdiction: 'United States',
    area: 'Consumer Protection',
    summary: "Federal Trade Commission false advertising investigation into Udemy\'s marketing practices, specifically allegations of misleading course completion rates and inflated job placement statistics used in promotional materials. The FTC is examining whether Udemy\'s claims about student outcomes constituted deceptive acts under Section 5 of the FTC Act.",
    potentialExposureAmount: 25000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Civil penalties and consumer redress estimated at USD 25 million, plus injunctive relief requiring disclosure reforms.',
    status: 'Settlement Negotiations',
    riskLevel: 'High',
    riskScore: 65,
    riskRationale: 'FTC has been aggressive in EdTech enforcement following similar actions against other online learning platforms. Settlement negotiations are progressing but FTC is seeking significant consumer redress fund. The advertising claims in question were used broadly from 2019-2023, creating substantial potential liability period.',
    lastUpdated: '2024-09-01',
    submittedBy: 'Sarah Johnson',
  },
  {
    id: '6',
    caseNumber: 'PRX-2024-UK-006',
    companyName: 'Stack Overflow',
    dateStarted: '2024-02-14',
    regulator: 'ICO',
    jurisdiction: 'United Kingdom',
    area: 'Data Privacy',
    summary: "Information Commissioner\'s Office GDPR non-compliance investigation regarding Stack Overflow\'s handling of user data and third-party sharing practices. Key concerns include inadequate consent mechanisms for data sharing with advertising partners, insufficient data retention policies, and questions about the legal basis for processing user behaviour data for commercial purposes.",
    potentialExposureAmount: 18000000,
    potentialExposureCriminal: false,
    exposureDescription: 'GDPR fines up to 4% of global annual turnover estimated at GBP 14 million, plus mandatory remediation costs.',
    status: 'Monitoring',
    riskLevel: 'Medium',
    riskScore: 52,
    riskRationale: "ICO has indicated openness to a compliance-focused resolution rather than punitive action, particularly given Stack Overflow\'s proactive engagement. However, the investigation scope is broader than initially disclosed, covering practices dating to 2018. The technical developer community nature of the user base heightens reputational risk beyond financial exposure.",
    lastUpdated: '2024-07-30',
    submittedBy: 'Emma Clarke',
  },
  {
    id: '7',
    caseNumber: 'PRX-2023-RO-007',
    companyName: 'eMAG',
    dateStarted: '2023-01-10',
    regulator: 'ANPC',
    jurisdiction: 'Romania',
    area: 'Consumer Protection',
    summary: "Romanian National Authority for Consumer Protection investigation into eMAG\'s misleading return policies and hidden fees on marketplace transactions. Consumers reported significant discrepancies between advertised return windows and actual practice, plus undisclosed marketplace seller fees passed to consumers. The matter has been resolved through a negotiated compliance undertaking.",
    potentialExposureAmount: 8000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Administrative fines of RON 40 million plus mandatory consumer compensation scheme for affected customers.',
    status: 'Resolved',
    riskLevel: 'Low',
    riskScore: 28,
    riskRationale: "Matter resolved through voluntary compliance undertaking accepted by ANPC. eMAG implemented required policy changes and consumer compensation scheme. ANPC has confirmed compliance. Residual risk relates to potential civil class action from consumer groups, which remains unlikely given the regulator\'s positive assessment of remediation.",
    lastUpdated: '2024-03-15',
    submittedBy: 'Mihai Ionescu',
  },
  {
    id: '8',
    caseNumber: 'PRX-2023-ZA-008',
    companyName: 'Takealot',
    dateStarted: '2023-08-22',
    regulator: 'CGSO',
    jurisdiction: 'South Africa',
    area: 'Consumer Protection',
    summary: "Consumer Goods and Services Ombud investigation into Takealot\'s marketplace seller dispute resolution process and systemic consumer refund failures. Investigation focuses on delays in processing legitimate refunds, inadequate seller accountability mechanisms, and the effectiveness of Takealot\'s internal dispute resolution procedures for marketplace transactions.",
    potentialExposureAmount: 15000000,
    potentialExposureCriminal: false,
    exposureDescription: 'CGSO remediation orders plus potential CPA referral fines estimated at ZAR 275 million, plus mandatory process overhaul costs.',
    status: 'Settlement Negotiations',
    riskLevel: 'Medium',
    riskScore: 41,
    riskRationale: "Settlement discussions are advanced with CGSO indicating acceptance of Takealot\'s remediation plan. The main outstanding issue is the quantum of consumer compensation. Takealot\'s dominant position in South African ecommerce means the CGSO is motivated to achieve systemic change rather than punitive outcomes. Financial exposure is manageable.",
    lastUpdated: '2024-06-10',
    submittedBy: 'Thabo Nkosi',
  },
  {
    id: '9',
    caseNumber: 'PRX-2023-IN-009',
    companyName: 'Meesho',
    dateStarted: '2023-04-18',
    regulator: 'ED (Enforcement Directorate)',
    jurisdiction: 'India',
    area: 'Financial Services',
    summary: 'Enforcement Directorate investigation into alleged foreign exchange violations by Meesho under the Foreign Exchange Management Act (FEMA). The investigation focuses on alleged irregular cross-border payment flows, undisclosed related party transactions with overseas affiliates, and potential misclassification of remittances to circumvent RBI approval requirements for foreign investments.',
    potentialExposureAmount: 65000000,
    potentialExposureCriminal: true,
    exposureDescription: 'FEMA penalties up to three times the transaction amount estimated at USD 65 million, plus potential criminal prosecution of directors under FEMA Section 13.',
    status: 'Litigation',
    riskLevel: 'Critical',
    riskScore: 91,
    riskRationale: 'ED investigations with criminal dimensions represent the highest risk category. The Enforcement Directorate has broad powers including asset attachment and arrest of executives. The alleged FEMA violations involve complex multi-jurisdictional payment structures that are difficult to defend. Criminal exposure for directors creates significant personal liability risk and governance implications. Immediate board-level attention required.',
    lastUpdated: '2024-08-05',
    submittedBy: 'Rohit Agarwal',
  },
  {
    id: '10',
    caseNumber: 'PRX-2023-FR-010',
    companyName: 'Brainly',
    dateStarted: '2023-12-01',
    regulator: 'CNIL',
    jurisdiction: 'France',
    area: 'Data Privacy',
    summary: "French data protection authority CNIL investigation into Brainly\'s GDPR violations related to the processing of personal data belonging to minors without verifiable parental consent. The investigation examines Brainly\'s age verification mechanisms, the adequacy of consent flows for users under 15, and the commercial use of student data for targeted advertising.",
    potentialExposureAmount: 35000000,
    potentialExposureCriminal: false,
    exposureDescription: 'GDPR fines up to 4% of global annual turnover estimated at EUR 32 million, plus mandatory technical remediation.',
    status: 'Under Investigation',
    riskLevel: 'High',
    riskScore: 74,
    riskRationale: "CNIL has been highly active in children\'s data protection enforcement following European DPA coordination. The processing of minors\' data for advertising purposes is an aggravating factor. Brainly\'s global user base includes a significant proportion of under-15 users, making the scale of potential violations substantial. Precedents from similar cases suggest fines in the EUR 20-35 million range.",
    lastUpdated: '2024-07-22',
    submittedBy: 'Sophie Dubois',
  },
  {
    id: '11',
    caseNumber: 'PRX-2022-DE-011',
    companyName: 'OLX Germany',
    dateStarted: '2022-07-30',
    regulator: 'Bundeskartellamt',
    jurisdiction: 'Germany',
    area: 'Competition',
    summary: "Bundeskartellamt merger review complications following OLX Germany\'s acquisition of AutoScout24 assets, triggering significant market dominance concerns in the German online automotive classifieds market. The authority is examining whether the combined entity would create a dominant position foreclosing competition, and whether proposed remedies are sufficient to address competitive concerns.",
    potentialExposureAmount: 200000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Potential mandatory divestiture of acquired assets valued at EUR 180 million, plus transaction costs and opportunity costs of blocked strategy.',
    status: 'Litigation',
    riskLevel: 'Critical',
    riskScore: 85,
    riskRationale: "Bundeskartellamt has been one of Europe\'s most aggressive competition authorities. The combined market share in automotive classifieds would exceed 70%, making dominance finding highly probable. The authority has indicated structural remedies (divestitures) rather than behavioural remedies would be required. Litigation risk is elevated as the authority rejected initial remedy proposals.",
    lastUpdated: '2024-09-10',
    submittedBy: 'Klaus Weber',
  },
  {
    id: '12',
    caseNumber: 'PRX-2024-CA-012',
    companyName: 'PayU Canada',
    dateStarted: '2024-03-10',
    regulator: 'FINTRAC',
    jurisdiction: 'Canada',
    area: 'Financial Services',
    summary: "Financial Transactions and Reports Analysis Centre of Canada AML compliance failures investigation, including inadequate transaction monitoring systems, deficient suspicious activity reporting (SAR) processes, and gaps in know-your-customer (KYC) procedures. FINTRAC identified systemic compliance program deficiencies during a routine examination of PayU\'s Canadian operations.",
    potentialExposureAmount: 22000000,
    potentialExposureCriminal: true,
    exposureDescription: 'Administrative monetary penalties up to CAD 30 million per violation plus potential criminal prosecution referral to RCMP for wilful non-compliance.',
    status: 'Under Investigation',
    riskLevel: 'High',
    riskScore: 78,
    riskRationale: "FINTRAC has significantly increased enforcement activity following Canada\'s FATF mutual evaluation findings. Criminal referral risk is elevated by the systemic nature of the compliance gaps identified. PayU Canada has engaged external AML specialists and is implementing remediation, but FINTRAC examinations typically result in substantial penalties even where remediation is underway.",
    lastUpdated: '2024-08-15',
    submittedBy: 'Marie Tremblay',
  },
  {
    id: '13',
    caseNumber: 'PRX-2023-IN-013',
    companyName: 'Swiggy',
    dateStarted: '2023-07-15',
    regulator: 'Ministry of Labour & Employment',
    jurisdiction: 'India',
    area: 'Employment',
    summary: "Indian Labour Ministry gig worker classification dispute challenging Swiggy\'s classification of delivery partners as independent contractors rather than employees. The dispute concerns entitlement to statutory benefits including provident fund contributions, health insurance, minimum wage protections, and termination rights. Multiple delivery partner unions have filed formal complaints triggering ministry review.",
    potentialExposureAmount: 40000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Retrospective social security contributions, back pay for minimum wage shortfalls, and gratuity obligations estimated at INR 3.3 billion.',
    status: 'Monitoring',
    riskLevel: 'Medium',
    riskScore: 55,
    riskRationale: "India\'s Code on Social Security 2020 created a new gig worker category but implementing rules remain incomplete, creating legal uncertainty. The Ministry has been reluctant to force reclassification given the employment impact. However, Supreme Court litigation on similar issues in other sectors could set adverse precedent. The exposure estimate assumes partial reclassification of highest-engagement delivery partners.",
    lastUpdated: '2024-05-30',
    submittedBy: 'Priya Sharma',
  },
  {
    id: '14',
    caseNumber: 'PRX-2023-BR-014',
    companyName: 'iFood',
    dateStarted: '2023-05-20',
    regulator: 'Receita Federal',
    jurisdiction: 'Brazil',
    area: 'Tax',
    summary: "Brazilian Federal Revenue Service transfer pricing violations investigation into iFood\'s intragroup service fees and royalty payment arrangements. Receita Federal is examining whether the pricing of intercompany transactions between iFood Brazil and related entities in Luxembourg and Netherlands reflects arm\'s length pricing, with specific focus on technology licensing fees and management service charges.",
    potentialExposureAmount: 120000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Tax assessments including penalties and interest estimated at BRL 600 million, covering assessment years 2019-2023.',
    status: 'Under Investigation',
    riskLevel: 'High',
    riskScore: 80,
    riskRationale: "Brazilian transfer pricing rules are being aligned with OECD standards from 2024, creating transitional complexity. Receita Federal has been increasingly aggressive in platform economy transfer pricing audits. The multi-year assessment period and size of intercompany flows create substantial exposure. iFood\'s dominant market position and high margins make the pricing of intangibles difficult to defend at current levels.",
    lastUpdated: '2024-09-05',
    submittedBy: 'Rafael Costa',
  },
];
