import { RegulatoryMatter } from './types';

export const seedMatters: RegulatoryMatter[] = [
  {
    id: '1',
    caseNumber: 'REG-2024-001',
    companyName: 'iFood',
    dateStarted: '2023-08-14',
    regulator: 'CADE',
    jurisdiction: 'Brazil',
    area: 'Competition',
    summary: 'CADE is investigating iFood for alleged abuse of dominant position in the Brazilian food delivery market, specifically related to exclusivity clauses imposed on restaurant partners that restrict their ability to operate on competing platforms. The investigation follows complaints from OLX, Rappi and smaller operators.',
    potentialExposureAmount: 85000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Administrative fine of up to 20% of gross revenues in Brazil, estimated at BRL 450M (~USD 85M). Possible mandatory unwinding of exclusivity agreements.',
    status: 'Under Investigation',
    riskLevel: 'Critical',
    riskScore: 88,
    riskRationale: 'iFood holds approximately 80% market share in Brazil\'s food delivery sector. CADE has precedent for imposing maximum-range fines in dominance abuse cases. The exclusivity clause evidence is reportedly documentary, reducing litigation uncertainty. Reputational spillover to Prosus portfolio material.',
    lastUpdated: '2024-11-20',
    submittedBy: 'Ana Carvalho',
  },
  {
    id: '2',
    caseNumber: 'REG-2024-002',
    companyName: 'Meesho',
    dateStarted: '2023-11-02',
    regulator: 'Enforcement Directorate (ED)',
    jurisdiction: 'India',
    area: 'Financial Services',
    summary: 'The Enforcement Directorate is investigating Meesho for alleged violations of the Foreign Exchange Management Act (FEMA), specifically relating to the routing of foreign investment proceeds and cross-border payment flows that may not have complied with RBI reporting requirements.',
    potentialExposureAmount: 65000000,
    potentialExposureCriminal: true,
    exposureDescription: 'FEMA violations carry penalties up to three times the amount involved (~USD 65M) plus potential criminal prosecution of directors under PMLA. Key officers face personal liability.',
    status: 'Under Investigation',
    riskLevel: 'Critical',
    riskScore: 91,
    riskRationale: 'Criminal exposure under PMLA elevates this to Critical regardless of ultimate financial quantum. ED investigations in India frequently escalate to asset attachment orders which could disrupt operations. Individual director liability creates governance risk for Prosus board representatives.',
    lastUpdated: '2024-12-01',
    submittedBy: 'Priya Nair',
  },
  {
    id: '3',
    caseNumber: 'REG-2024-003',
    companyName: 'OLX',
    dateStarted: '2022-05-18',
    regulator: 'Bundeskartellamt',
    jurisdiction: 'Germany',
    area: 'Competition',
    summary: 'The German Federal Cartel Office is reviewing OLX\'s proposed acquisition of Scout24\'s ImmoScout24 division. The authority has raised Phase II concerns about the combined entity\'s dominance in online classifieds for real estate and automotive categories across DACH markets.',
    potentialExposureAmount: 200000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Potential prohibition of the transaction (deal value EUR 180M). If remedies required, estimated divestiture cost of EUR 40-70M. Legal and advisory fees already at EUR 8M.',
    status: 'Litigation',
    riskLevel: 'Critical',
    riskScore: 82,
    riskRationale: 'Bundeskartellamt has blocked major digital mergers in recent years. Combined market share would exceed 65% in German real estate classifieds. Strategic value of the acquisition to OLX makes prohibition or heavy remedies a material setback. Timeline extending into 2025 creates management distraction.',
    lastUpdated: '2024-10-15',
    submittedBy: 'Klaus Weber',
  },
  {
    id: '4',
    caseNumber: 'REG-2024-004',
    companyName: 'iFood',
    dateStarted: '2024-01-10',
    regulator: 'Receita Federal',
    jurisdiction: 'Brazil',
    area: 'Tax',
    summary: 'Brazil\'s Receita Federal has initiated a transfer pricing audit covering 2019–2022, examining intercompany service fees paid by iFood to its Dutch holding structure and the allocation of IP licensing income. The authority contends that arm\'s length pricing was not applied to technology platform licenses.',
    potentialExposureAmount: 120000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Back taxes, interest, and penalties estimated at BRL 600M (~USD 120M) if the authority\'s proposed adjustments are upheld in full. Appeal process may extend 5-7 years.',
    status: 'Under Investigation',
    riskLevel: 'High',
    riskScore: 74,
    riskRationale: 'Brazil has adopted OECD transfer pricing rules effective 2024, signalling increased enforcement rigour. The IP licensing arrangements are a common audit target. However, iFood has strong external TP documentation and the arm\'s length position is defensible at appeal. Long timeline reduces near-term cash impact.',
    lastUpdated: '2024-11-05',
    submittedBy: 'Ana Carvalho',
  },
  {
    id: '5',
    caseNumber: 'REG-2023-005',
    companyName: 'Swiggy',
    dateStarted: '2022-09-30',
    regulator: 'Competition Commission of India (CCI)',
    jurisdiction: 'India',
    area: 'Antitrust',
    summary: 'CCI is investigating Swiggy and Zomato jointly for allegedly imposing exclusivity restrictions on restaurant partners and discriminatory commission structures that favour certain restaurant chains. Swiggy is also under scrutiny for its Swiggy One subscription\'s preferential listing practices.',
    potentialExposureAmount: 30000000,
    potentialExposureCriminal: false,
    exposureDescription: 'CCI fines typically range 0-10% of average turnover. Estimated exposure USD 25-35M. Potential mandatory operational changes to commission structure estimated at USD 15M annual revenue impact.',
    status: 'Settlement Negotiations',
    riskLevel: 'High',
    riskScore: 68,
    riskRationale: 'CCI has recently shown willingness to impose significant fines on major platforms. Settlement talks are progressing but involve structural remedies. Zomato\'s parallel matter creates coordinated risk. Post-IPO public scrutiny amplifies reputational dimension.',
    lastUpdated: '2024-09-22',
    submittedBy: 'Rajesh Kumar',
  },
  {
    id: '6',
    caseNumber: 'REG-2024-006',
    companyName: 'Brainly',
    dateStarted: '2023-06-15',
    regulator: 'CNIL',
    jurisdiction: 'France',
    area: 'Data Privacy',
    summary: 'The French data protection authority CNIL has initiated formal proceedings against Brainly following complaints from child protection organisations. The investigation centres on the collection of behavioural data from users under 16, inadequate parental consent mechanisms, and the use of targeted advertising profiles for minors.',
    potentialExposureAmount: 35000000,
    potentialExposureCriminal: false,
    exposureDescription: 'GDPR maximum fine of 4% of global annual turnover, estimated at EUR 30-32M. CNIL has previously issued fines in the EUR 5-150M range for GDPR violations. Potential requirement to delete existing minor user profiles.',
    status: 'Under Investigation',
    riskLevel: 'High',
    riskScore: 72,
    riskRationale: 'CNIL and other EU DPAs have intensified enforcement on children\'s data following UK ICO precedents. Brainly\'s core user base is minors, making structural compliance changes potentially business-model-threatening. GDPR coordination with Polish DPA (Brainly HQ) adds jurisdictional complexity.',
    lastUpdated: '2024-10-30',
    submittedBy: 'Sophie Leclerc',
  },
  {
    id: '7',
    caseNumber: 'REG-2023-007',
    companyName: 'PayU',
    dateStarted: '2023-03-22',
    regulator: 'Reserve Bank of India (RBI)',
    jurisdiction: 'India',
    area: 'Data Privacy',
    summary: 'RBI conducted a supervisory audit of PayU\'s payment aggregator operations and identified deficiencies in data localisation compliance — specifically, certain transaction data was found to be processed on servers outside India contrary to RBI\'s Payment Aggregator Guidelines. A show cause notice was issued in March 2023.',
    potentialExposureAmount: 12000000,
    potentialExposureCriminal: false,
    exposureDescription: 'RBI financial penalties for payment system violations estimated at INR 1-2B (~USD 12-24M). Risk of temporary suspension of PA licence pending compliance certification.',
    status: 'Monitoring',
    riskLevel: 'Medium',
    riskScore: 55,
    riskRationale: 'PayU has substantially remediated the technical non-compliance and submitted a detailed response to the show cause notice. RBI has not escalated to enforcement action. Residual risk relates to licence suspension during the certification period. Financial penalty likely at lower end of range given cooperation.',
    lastUpdated: '2024-08-14',
    submittedBy: 'Vikram Mehta',
  },
  {
    id: '8',
    caseNumber: 'REG-2024-008',
    companyName: 'PayU',
    dateStarted: '2024-02-07',
    regulator: 'FINTRAC',
    jurisdiction: 'Canada',
    area: 'Financial Services',
    summary: 'FINTRAC (Canada\'s financial intelligence unit) identified deficiencies in PayU Canada\'s AML/KYC programme following a routine compliance examination. Issues include inadequate beneficial ownership verification for merchant onboarding and gaps in suspicious transaction reporting protocols.',
    potentialExposureAmount: 22000000,
    potentialExposureCriminal: true,
    exposureDescription: 'FINTRAC administrative penalties up to CAD 500K per violation; criminal prosecution of officers under PCMLTFA could apply if wilful non-compliance is found. Total estimated exposure USD 18-22M including remediation costs.',
    status: 'Under Investigation',
    riskLevel: 'High',
    riskScore: 70,
    riskRationale: 'Criminal officer liability under PCMLTFA is a material concern even if ultimate risk is administrative. PayU\'s Canada operations are growing and a FINTRAC public finding would damage merchant confidence. The AML gaps appear systemic rather than isolated, suggesting broader programme investment needed.',
    lastUpdated: '2024-11-12',
    submittedBy: 'Vikram Mehta',
  },
  {
    id: '9',
    caseNumber: 'REG-2023-009',
    companyName: 'Udemy',
    dateStarted: '2022-11-08',
    regulator: 'Federal Trade Commission (FTC)',
    jurisdiction: 'United States',
    area: 'Consumer Protection',
    summary: 'The FTC is investigating Udemy\'s marketing practices, specifically allegations that course outcome claims ("Get a job as a data scientist in 90 days") constitute deceptive advertising under Section 5 of the FTC Act. The investigation also covers automatic subscription renewal practices and refund policy enforcement.',
    potentialExposureAmount: 25000000,
    potentialExposureCriminal: false,
    exposureDescription: 'FTC civil penalties up to USD 50,000 per violation. Class action exposure from private plaintiffs estimated at USD 15-25M. Consent decree obligations including revised marketing standards and consumer refund programme.',
    status: 'Settlement Negotiations',
    riskLevel: 'High',
    riskScore: 65,
    riskRationale: 'FTC has been aggressive on edtech marketing since 2022. Settlement is likely but consent decree terms may constrain Udemy\'s core marketing approach. Class action plaintiffs are coordinating with FTC investigation timeline. Reputational risk to Udemy brand in a competitive market.',
    lastUpdated: '2024-10-08',
    submittedBy: 'Jennifer Walsh',
  },
  {
    id: '10',
    caseNumber: 'REG-2023-010',
    companyName: 'Stack Overflow',
    dateStarted: '2023-01-19',
    regulator: 'Information Commissioner\'s Office (ICO)',
    jurisdiction: 'United Kingdom',
    area: 'Data Privacy',
    summary: 'ICO initiated an inquiry following a complaint by a UK-based developer community group alleging that Stack Overflow\'s cookie consent mechanism did not meet GDPR/UK GDPR standards — specifically that non-essential cookies were set prior to affirmative user consent, and that the consent withdrawal mechanism was not equally prominent.',
    potentialExposureAmount: 18000000,
    potentialExposureCriminal: false,
    exposureDescription: 'UK GDPR fine up to GBP 17.5M or 4% of global turnover. ICO has scaled fines to GBP 7-15M for cookie consent violations by major platforms. Compliance remediation estimated at GBP 2M.',
    status: 'Monitoring',
    riskLevel: 'Medium',
    riskScore: 48,
    riskRationale: 'Stack Overflow has deployed a revised consent management platform and submitted evidence to ICO. The ICO inquiry is in an inactive review phase. Fine risk is moderate — Stack Overflow\'s revenues make the proportionality ceiling low. Precedent risk to Prosus other digital portfolio companies is the main concern.',
    lastUpdated: '2024-07-30',
    submittedBy: 'David Okafor',
  },
  {
    id: '11',
    caseNumber: 'REG-2024-011',
    companyName: 'Swiggy',
    dateStarted: '2024-03-01',
    regulator: 'Ministry of Labour & Employment',
    jurisdiction: 'India',
    area: 'Employment',
    summary: 'Following the Code on Social Security 2020 notification, India\'s Labour Ministry is scrutinising Swiggy\'s gig worker classification model. Inspectors have audited delivery partner contracts and allege that Swiggy exercises sufficient control to require classification as employees, entitling workers to PF, ESI and gratuity benefits.',
    potentialExposureAmount: 40000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Retroactive provident fund contributions for ~300,000 delivery partners estimated at INR 15-25B (~USD 35-40M) if reclassification is ordered. Ongoing cost increase of USD 80-100M annually if employment model mandated.',
    status: 'Under Investigation',
    riskLevel: 'High',
    riskScore: 66,
    riskRationale: 'Gig worker classification is a systemic issue across the Indian gig economy but Swiggy faces lead-company scrutiny. The ongoing cost impact exceeds the back-payment exposure and is the real strategic risk. Legislative resolution may supersede enforcement action but timeline is uncertain. Zomato faces parallel proceedings.',
    lastUpdated: '2024-11-25',
    submittedBy: 'Rajesh Kumar',
  },
  {
    id: '12',
    caseNumber: 'REG-2022-012',
    companyName: 'eMAG',
    dateStarted: '2022-04-05',
    regulator: 'ANPC',
    jurisdiction: 'Romania',
    area: 'Consumer Protection',
    summary: 'Romania\'s National Authority for Consumer Protection (ANPC) issued findings that eMAG\'s standard return policy failed to adequately communicate consumers\' statutory 14-day withdrawal right under EU Directive 2011/83, and that certain "final sale" designations were applied in breach of consumer protection law.',
    potentialExposureAmount: 8000000,
    potentialExposureCriminal: false,
    exposureDescription: 'ANPC fines up to RON 100,000 per violation. Total exposure estimated at RON 40M (~USD 8M) including consumer redress programme. eMAG\'s Romanian operations generate annual revenues of ~EUR 1.2B.',
    status: 'Resolved',
    riskLevel: 'Low',
    riskScore: 22,
    riskRationale: 'Matter resolved via agreed undertakings and consumer redress programme in Q2 2024. ANPC lifted monitoring status. Residual risk is reputational in the Romanian market. Financial impact was within provisioned amounts. No structural changes to business model required.',
    lastUpdated: '2024-06-15',
    submittedBy: 'Mihai Popescu',
  },
  {
    id: '13',
    caseNumber: 'REG-2023-013',
    companyName: 'Takealot',
    dateStarted: '2023-07-12',
    regulator: 'Consumer Goods and Services Ombud (CGSO)',
    jurisdiction: 'South Africa',
    area: 'Consumer Protection',
    summary: 'The CGSO received 847 complaints against Takealot in H1 2023, triggering a systemic investigation into alleged unfair trading practices including misleading pricing displays (artificial pre-discount inflation), non-delivery without adequate remedy, and warranty claim denial practices on marketplace third-party sellers.',
    potentialExposureAmount: 15000000,
    potentialExposureCriminal: false,
    exposureDescription: 'Consumer Protection Act penalties up to 10% of annual turnover (ZAR ~3B, implying ZAR 300M cap). Practical exposure estimated at ZAR 280M (~USD 15M) plus voluntary consumer redress. CGSO may refer to NCC for further enforcement.',
    status: 'Under Investigation',
    riskLevel: 'Medium',
    riskScore: 52,
    riskRationale: 'CGSO investigations rarely result in maximum penalties. Takealot has initiated voluntary remediation and engaged proactively. Primary risk is referral to the National Consumer Commission and associated reputational damage. South African consumer sentiment toward Takealot is a competitive vulnerability.',
    lastUpdated: '2024-09-03',
    submittedBy: 'Thabo Nkosi',
  },
  {
    id: '14',
    caseNumber: 'REG-2022-014',
    companyName: 'OLX',
    dateStarted: '2021-10-22',
    regulator: 'European Commission (DG COMP)',
    jurisdiction: 'European Union',
    area: 'Competition',
    summary: 'DG COMP commenced a sector inquiry into online classifieds and C2C marketplaces. OLX, as one of the largest EU-wide operators, received a formal information request covering pricing algorithms, data sharing with third-party advertisers, and MFN clauses in seller agreements. The sector inquiry may lead to individual investigations.',
    potentialExposureAmount: 45000000,
    potentialExposureCriminal: false,
    exposureDescription: 'EC fines for competition violations up to 10% of global turnover. If an individual investigation follows and infringement is found, exposure could reach EUR 40-50M. Sector inquiry itself carries no direct fine risk.',
    status: 'Monitoring',
    riskLevel: 'Medium',
    riskScore: 44,
    riskRationale: 'Sector inquiries infrequently lead to individual enforcement in the near term. OLX has cooperated fully with information requests. The DMA framework may supersede competition enforcement for some conduct. Risk is low probability but high consequence if escalated to individual investigation. Monitoring recommended.',
    lastUpdated: '2024-05-20',
    submittedBy: 'Klaus Weber',
  },
];
